# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: | 
    sudo apt-get update
    sudo apt-get install build-essential
    sudo apt-get install libspdlog-dev
    sudo apt install libsdl2-dev
    sudo apt install libsdl2-image-dev
    sudo apt install libsdl2-ttf-dev
    sudo apt install libsdl2-mixer-dev
    cmake -S . -B ./build
    cmake --build ./build
  displayName: 'ubuntu gcc build'

- script: |
    ctest --test-dir ./build -VV
  displayName: 'unittests'
